### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rtorresjunior** [sreichel/magento-Sr-GDRT#2]
Hi, I got this error on 1.9.3.8
On front and backend

Fatal error: Can't use function return value in write context in /app/code/community/Sr/Gdrt/Helper/Data.php on line 62

this line it's `return Mage::getStoreConfigFlag(self::XML_PATH_ENABLED) && !empty(Mage::getStoreConfig(self::XML_PATH_COVERSION_ID));`

any idea what is happening on this case?

**Comment by sreichel** [comment]
Wich PHP do you use? (https://stackoverflow.com/a/2173318/5703627)

**Comment by rtorresjunior** [comment]
It's PHP 5.6 version.
